all:
  hosts:
    master-node:
      ansible_host: masterNode
      ip: masterNode
      access_ip: masterNode
    node1:
      ansible_host: nodeOne
      ip: nodeOne
      access_ip: nodeOne
    node2:
      ansible_host: nodeTwo
      ip: nodeTwo
      access_ip: nodeTwo
    node3:
      ansible_host: nodeThree
      ip: nodeThree
      access_ip: nodeThree
  children:
    kube-master:
      hosts:
        master-node:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        master-node:
        node1:
        node2:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
